# Generated by Django 2.1.1 on 2018-09-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyvideo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_rental_app.Video'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
    ]
