# Generated by Django 2.1.1 on 2018-09-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='video',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
