# Generated by Django 2.1.1 on 2018-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0002_auto_20180917_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
