# Generated by Django 2.1.1 on 2018-09-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0003_auto_20180906_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='actual_video',
            field=models.ImageField(upload_to=''),
        ),
    ]
