# Generated by Django 2.1.1 on 2018-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
