# Generated by Django 2.1.1 on 2018-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0004_video_preview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview_video',
            field=models.FileField(upload_to=''),
        ),
    ]
