# Generated by Django 2.1.1 on 2018-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0007_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
