# Generated by Django 2.1.1 on 2018-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_rental_app', '0008_userinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
